/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

'use strict';

var obsidian = require('obsidian');
var child_process = require('child_process');
var util = require('util');

/******************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */

function __awaiter(thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
}

const DEFAULT_SETTINGS = {
    fcitxRemotePath_macOS: '/usr/local/bin/fcitx-remote',
    fcitxRemotePath_windows: 'C:\\Program Files\\bin\\fcitx-remote',
    fcitxRemotePath_linux: '/usr/bin/fcitx-remote',
};
const pexec = util.promisify(child_process.exec);
var IMStatus;
(function (IMStatus) {
    IMStatus[IMStatus["None"] = 0] = "None";
    IMStatus[IMStatus["Activate"] = 1] = "Activate";
    IMStatus[IMStatus["Deactivate"] = 2] = "Deactivate";
})(IMStatus || (IMStatus = {}));
class VimIMSwitchPlugin extends obsidian.Plugin {
    constructor() {
        super(...arguments);
        this.imStatus = IMStatus.None;
        this.fcitxRemotePath = "";
        this.editorMode = null;
        this.initialized = false;
        this.cmEditor = null;
        this.onVimModeChange = (cm) => __awaiter(this, void 0, void 0, function* () {
            if (cm.mode == "normal" || cm.mode == "visual") {
                yield this.getFcitxRemoteStatus();
                if (this.imStatus == IMStatus.Activate) {
                    yield this.deactivateIM();
                }
            }
            else if (cm.mode == "insert" || cm.mode == "replace") {
                if (this.imStatus == IMStatus.Activate) {
                    yield this.activateIM();
                }
            }
        });
    }
    onload() {
        return __awaiter(this, void 0, void 0, function* () {
            console.log('loading plugin VimIMSwitchPlugin.');
            yield this.loadSettings();
            // this.addStatusBarItem().setText('Vim IM Swith Enabled');
            this.addSettingTab(new IMSwitchSettingTab(this.app, this));
            this.app.workspace.on('file-open', (file) => __awaiter(this, void 0, void 0, function* () {
                console.log("file-open");
                if (!this.initialized)
                    yield this.initialize();
                // {mode: string, ?subMode: string} object. Modes: "insert", "normal", "replace", "visual". Visual sub-modes: "linewise", "blockwise"}
                if (this.cmEditor) {
                    // default is normal mode, try to deactivate the IM.
                    yield this.deactivateIM();
                    this.cmEditor.off("vim-mode-change", this.onVimModeChange);
                    this.cmEditor.on("vim-mode-change", this.onVimModeChange);
                }
            }));
            // Used when we open a new markdown view by "split vertically", 
            // which will not trigger 'file-open' event on obsidian v0.15.6
            this.app.workspace.on('active-leaf-change', (leaf) => __awaiter(this, void 0, void 0, function* () {
                console.log("active-leaf-change");
                if (this.app.workspace.activeLeaf.view.getViewType() == "markdown") {
                    console.log("focus on markdown view");
                    if (!this.initialized)
                        yield this.initialize();
                    // {mode: string, ?subMode: string} object. Modes: "insert", "normal", "replace", "visual". Visual sub-modes: "linewise", "blockwise"}
                    if (this.cmEditor) {
                        // default is normal mode, try to deactivate the IM.
                        yield this.deactivateIM();
                        this.cmEditor.off("vim-mode-change", this.onVimModeChange);
                        this.cmEditor.on("vim-mode-change", this.onVimModeChange);
                    }
                }
            }));
        });
    }
    initialize() {
        var _a, _b, _c, _d;
        return __awaiter(this, void 0, void 0, function* () {
            if (this.initialized)
                return;
            console.log("initialize");
            // Determine if we have the legacy Obsidian editor (CM5) or the new one (CM6).
            // This is only available after Obsidian is fully loaded, so we do it as part of the `file-open` event.
            if ('editor:toggle-source' in this.app.commands.editorCommands) {
                this.editorMode = 'cm6';
                console.log('VimIMSwitchPlugin: using CodeMirror 6 mode');
            }
            else {
                this.editorMode = 'cm5';
                console.log('VimIMSwitchPlugin: using CodeMirror 5 mode');
            }
            // For CM6 this actually returns an instance of the object named CodeMirror from cm_adapter of codemirror_vim
            const view = this.app.workspace.getActiveViewOfType(obsidian.MarkdownView);
            if (this.editorMode == 'cm6')
                this.cmEditor = (_c = (_b = (_a = view.sourceMode) === null || _a === void 0 ? void 0 : _a.cmEditor) === null || _b === void 0 ? void 0 : _b.cm) === null || _c === void 0 ? void 0 : _c.cm;
            else
                this.cmEditor = (_d = view.sourceMode) === null || _d === void 0 ? void 0 : _d.cmEditor;
        });
    }
    runCmd(cmd, args = []) {
        return __awaiter(this, void 0, void 0, function* () {
            const output = yield pexec(`${cmd} ${args.join(" ")}`);
            return output.stdout;
        });
    }
    getFcitxRemoteStatus() {
        return __awaiter(this, void 0, void 0, function* () {
            if (this.fcitxRemotePath == "") {
                console.log("VIM-IM-Switch-pugin: cannot get fcitx-remote path, please set it correctly.");
                return;
            }
            let fcitxRemoteOutput = yield this.runCmd(this.fcitxRemotePath);
            fcitxRemoteOutput = fcitxRemoteOutput.trimRight();
            if (fcitxRemoteOutput == "1") {
                this.imStatus = IMStatus.Deactivate;
            }
            else if (fcitxRemoteOutput == "2") {
                this.imStatus = IMStatus.Activate;
            }
            else {
                this.imStatus = IMStatus.None;
            }
            console.log("Vim-IM-Swith-plugin: IM status " + this.imStatus.toString());
        });
    }
    activateIM() {
        return __awaiter(this, void 0, void 0, function* () {
            if (this.fcitxRemotePath == "") {
                console.log("VIM-IM-Switch-pugin: cannot get fcitx-remote path, please set it correctly.");
                return;
            }
            const output = yield this.runCmd(this.fcitxRemotePath, ["-o"]);
            console.log("Vim-IM-Swith-plugin: activate IM " + output);
        });
    }
    deactivateIM() {
        return __awaiter(this, void 0, void 0, function* () {
            if (this.fcitxRemotePath == "") {
                console.log("VIM-IM-Switch-pugin: cannot get fcitx-remote path, please set it correctly.");
                return;
            }
            const output = yield this.runCmd(this.fcitxRemotePath, ["-c"]);
            console.log("Vim-IM-Swith-plugin: deactivate IM " + output);
        });
    }
    onunload() {
        if (this.cmEditor) {
            this.cmEditor.off("vim-mode-change", this.onVimModeChange);
        }
        console.log('unloading plugin VimIMSwitchPlugin.');
    }
    loadSettings() {
        return __awaiter(this, void 0, void 0, function* () {
            this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
            this.updateCurrentPath();
        });
    }
    updateCurrentPath() {
        return __awaiter(this, void 0, void 0, function* () {
            switch (process.platform) {
                case 'darwin':
                    this.fcitxRemotePath = this.settings.fcitxRemotePath_macOS;
                    break;
                case 'linux':
                    this.fcitxRemotePath = this.settings.fcitxRemotePath_linux;
                    break;
                case 'win32':
                    this.fcitxRemotePath = this.settings.fcitxRemotePath_windows;
                    break;
                default:
                    console.log('VIM-IM-Switch-plugin: does not support ' + process.platform + ' currently.');
                    break;
            }
        });
    }
    saveSettings() {
        return __awaiter(this, void 0, void 0, function* () {
            yield this.saveData(this.settings);
        });
    }
}
class IMSwitchSettingTab extends obsidian.PluginSettingTab {
    constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
    }
    display() {
        let { containerEl } = this;
        containerEl.empty();
        containerEl.createEl('h2', { text: 'Settings for Vim IM Switch plugin.' });
        new obsidian.Setting(containerEl)
            .setName('Fcitx Remote Path for macOS')
            .setDesc('The absolute path to fcitx-remote bin file on macOS.')
            .addText(text => text
            .setPlaceholder(DEFAULT_SETTINGS.fcitxRemotePath_macOS)
            .setValue(this.plugin.settings.fcitxRemotePath_macOS)
            .onChange((value) => __awaiter(this, void 0, void 0, function* () {
            this.plugin.settings.fcitxRemotePath_macOS = value;
            this.plugin.updateCurrentPath();
            yield this.plugin.saveSettings();
        })));
        new obsidian.Setting(containerEl)
            .setName('Fcitx Remote Path for Linux')
            .setDesc('The absolute path to fcitx-remote bin file on Linux.')
            .addText(text => text
            .setPlaceholder(DEFAULT_SETTINGS.fcitxRemotePath_linux)
            .setValue(this.plugin.settings.fcitxRemotePath_linux)
            .onChange((value) => __awaiter(this, void 0, void 0, function* () {
            this.plugin.settings.fcitxRemotePath_linux = value;
            this.plugin.updateCurrentPath();
            yield this.plugin.saveSettings();
        })));
        new obsidian.Setting(containerEl)
            .setName('Fcitx Remote Path for Windows')
            .setDesc('The absolute path to fcitx-remote bin file on Windows.')
            .addText(text => text
            .setPlaceholder(DEFAULT_SETTINGS.fcitxRemotePath_windows)
            .setValue(this.plugin.settings.fcitxRemotePath_windows)
            .onChange((value) => __awaiter(this, void 0, void 0, function* () {
            this.plugin.settings.fcitxRemotePath_windows = value;
            this.plugin.updateCurrentPath();
            yield this.plugin.saveSettings();
        })));
    }
}

module.exports = VimIMSwitchPlugin;


/* nosourcemap */